Work around the problem pasted below. A hint to fix this properly might be from the sites http://msdn.microsoft.com/library/default.asp?url=/library/en-us/vccore/html/_error_Compiler_Errors_when_Implementing_a_CObject.2d.Derived_Class.asp http://jamesthornton.com/eckel/TICPP-2nd-ed-Vol-one/Chapter11.html (search for "private copy-constructor")
The error:

../../include/cpaf/gui/initializer/widget.h: In copy constructor 
'cpaf::gui::initializer::Widget<cpaf::gui::PanelInitializer>::Widget(const 
cpaf::gui::initializer::Widget<cpaf::gui::PanelInitializer>&)':
../../include/cpaf/gui/initializer/object.h:112: error: 'cpaf::gui::initializer::Object<T>::Object(const 
cpaf::gui::initializer::Object<T>&) [with T = cpaf::gui::PanelInitializer]' is private
../../include/cpaf/gui/initializer/widget.h:58: error: within this context
../../include/cpaf/gui/initializer/panel.h: In copy constructor 
'cpaf::gui::initializer::Panel<cpaf::gui::PanelInitializer>::Panel(const 
cpaf::gui::initializer::Panel<cpaf::gui::PanelInitializer>&)':
../../include/cpaf/gui/initializer/panel.h:28: warning: synthesized method 
'cpaf::gui::initializer::Widget<cpaf::gui::PanelInitializer>::Widget(const 
cpaf::gui::initializer::Widget<cpaf::gui::PanelInitializer>&)' first required here
../../include/cpaf/gui/initializer/panel.h: In copy constructor 'cpaf::gui::PanelInitializer::PanelInitializer(const 
cpaf::gui::PanelInitializer&)':
../../include/cpaf/gui/initializer/panel.h:48: warning: synthesized method 
'cpaf::gui::initializer::Panel<cpaf::gui::PanelInitializer>::Panel(const 
cpaf::gui::initializer::Panel<cpaf::gui::PanelInitializer>&)' first required here
main.cpp: In member function 'virtual bool MyApp::init()':
main.cpp:132: warning: synthesized method 'cpaf::gui::PanelInitializer::PanelInitializer(const 
cpaf::gui::PanelInitializer&)' first required here

Bottom-line - (all?) derived classes seem to also need a private copy ctor if the parent class has it.
Note that stuff like cpaf::gui::initializer::PanelInitializer is also inherited from the Object<T> (where the 
private copy ctor exists) through Panel<T>.